name: 签到-计划任务
on: 
  schedule:
    - cron: '0 * * * *'
jobs:
  CheckIn-Now:
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ vars.config }}
    steps: 
      - name: "安装python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "安装依赖项"
        run: pip install requests
      - name: "拉取代码"
        uses: actions/checkout@v4
      - name: "运行程序"
        run: python -u run.py
      
